Update README.md
reactplay/docs pull request #25
Opened 2023-03-11 07:59 UTC by ArslanYM

Added Link to the original React Play repo
![rp](https://user-images.githubusercontent.com/104521101/224472651-142e6d96-b71b-4aa7-9ca5-b81d39d1ccb9.png)

2023-03-21 19:28 UTC, Sachin-chaurasiya commented on README.md
> +# Link to the original repo of ReactPlay:
Hello @ArslanYM , thanks for the PR,

Can we just put simple text link instead of putting the heading like this?

2023-03-21 19:39 UTC, Sachin-chaurasiya requested changes

2023-03-22 05:30 UTC, ArslanYM commented on README.md
> +# Link to the original repo of ReactPlay:
yeah that seems more sophisticated

2023-03-22 05:31 UTC, ArslanYM commented on README.md
> +# Link to the original repo of ReactPlay:
Shall I make the changes and add a pr ?

2023-03-22 05:33 UTC, Sachin-chaurasiya commented on README.md
> +# Link to the original repo of ReactPlay:
@ArslanYM , We already have the original repo link in the README, can you check?

2023-03-22 05:37 UTC, ArslanYM commented on README.md
> +# Link to the original repo of ReactPlay:
yeah but its not propely made :

![d](https://user-images.githubusercontent.com/104521101/226812139-e7a98fe3-f950-47ea-b09d-7e7c3b42b4d7.png)

2023-03-22 05:38 UTC, Sachin-chaurasiya commented on README.md
> +# Link to the original repo of ReactPlay:
Yeah, it should be a link, you can fix that.

2023-03-22 05:39 UTC, ArslanYM commented on README.md
> +# Link to the original repo of ReactPlay:
on it

2023-03-22 05:42 UTC, ArslanYM commented on README.md
> +# Link to the original repo of ReactPlay:
Works?

![new](https://user-images.githubusercontent.com/104521101/226812750-9a12742e-b74f-4518-9179-5f980864d141.png)

2023-03-22 05:44 UTC, ArslanYM commented on README.md
> +# Link to the original repo of ReactPlay:
@Sachin-chaurasiya

2023-03-22 05:54 UTC, ArslanYM commented on README.md
> +# Link to the original repo of ReactPlay:
PR #37  fixes the issue

2023-03-22 05:55 UTC, ArslanYM commented
Resolved in #37

2023-03-22 05:55 UTC, closed without merging