Docs rework
reactplay/docs pull request #32
Opened 2023-03-19 09:45 UTC by joypoddar

Updated `docs/intro.md` with improvements wrt issue #10 

Linking redundant issue #29 as recommended by @atapas.

2023-03-21 19:42 UTC, Sachin-chaurasiya requested changes

2023-03-21 19:42 UTC, Sachin-chaurasiya commented on .github/ISSUE_TEMPLATE/feature-req.yml
@joypoddar , you have separate PR for this changes here #31 .
only keep changes related to this PR.

2023-03-22 09:29 UTC, joypoddar commented on .github/ISSUE_TEMPLATE/feature-req.yml
@Sachin-chaurasiya I am new to contributing to OSS. I did create a separate PR, but somehow it pulled both the commits in this PR. I wanted the `docs: rework (6f0a27c)` commit here. I am not sure how to do that...

I appreciate your patience and understanding.

2023-03-22 10:30 UTC, Sachin-chaurasiya commented on .github/ISSUE_TEMPLATE/feature-req.yml
Hello @Sachin-chaurasiya , No worries, we learn by doing mistakes.

Here are the steps
- `git checkout main`
-  `git remote add upstream https://github.com/reactplay/docs.git`
-  `git fetch upstream`
-  `git merge upstream/main`
-  `git push origin main`

Once these steps are done, you can merge main branch into this branch

`git checkout doc-rework`
`git merge main`

Thanks.

2023-03-22 10:50 UTC, joypoddar commented on .github/ISSUE_TEMPLATE/feature-req.yml
@Sachin-chaurasiya  I have done the above steps. 

How do I resolve the changes you requested before the below comment? Do I leave it as it is as suggested by @atapas in discord or is there something else that I have to do?
> @joypoddar , you have separate PR for this changes here #31 . only keep changes related to this PR.

2023-03-22 14:09 UTC, Sachin-chaurasiya commented on .github/ISSUE_TEMPLATE/feature-req.yml
No worries @joypoddar, It's resolved.

2023-03-28 08:27 UTC, joypoddar commented
@Sachin-chaurasiya I am unable to view the changes requested

2023-03-29 08:49 UTC, Sachin-chaurasiya commented
> @Sachin-chaurasiya I am unable to view the changes requested

It's resolved @joypoddar

2023-03-29 08:51 UTC, Sachin-chaurasiya requested changes

2023-04-01 07:48 UTC, Sachin-chaurasiya approved these changes
Thanks for the PR @joypoddar

2023-04-01 07:59 UTC, atapas approved these changes

2023-04-01 07:59 UTC, merged