doc: updated create-play from react-play
reactplay/docs pull request #48
Opened 2023-04-01 05:41 UTC by supminn

2023-04-01 07:43 UTC, Sachin-chaurasiya approved these changes
Great work @supminn  🙌🏻,
Thanks for the contributions ✨

2023-04-01 07:56 UTC, atapas requested changes
We should have the name in title case

![image](https://user-images.githubusercontent.com/3633137/229273510-cf28c165-9343-4921-a667-26299fca3bfe.png)

2023-04-01 07:58 UTC, atapas requested changes
Add Discord info here. Remove Discussions

![image](https://user-images.githubusercontent.com/3633137/229273630-945cea15-a0cd-4d15-8c20-93c8eaa41792.png)

2023-04-01 15:52 UTC, Sachin-chaurasiya approved these changes

2023-04-02 07:58 UTC, atapas approved these changes

2023-04-02 07:58 UTC, merged