Updated README.md
reactplay/docs pull request #5
Opened 2022-10-02 09:09 UTC by Misterr-H

Fix of the #2 issue

2022-10-04 12:10 UTC, Sachin-chaurasiya commented
@Misterr-H , Can you link the related issue to this PR?

2022-10-04 12:13 UTC, Sachin-chaurasiya requested changes

2022-10-04 12:13 UTC, Sachin-chaurasiya commented on README.md
> +1. Clone the repository.
Can you add the command for cloning the repository?

2022-10-04 12:13 UTC, Sachin-chaurasiya commented on README.md
> +5. Make changes to the website and see the changes reflected in the browser.
```suggestion
5. Make changes to the code and see the changes reflected in the browser.
```

2022-10-04 12:13 UTC, Sachin-chaurasiya commented on README.md
> +4. Open http://localhost:3000/ in your browser to view the website.
```suggestion
4. Visit http://localhost:3000/ in your browser to view the website.
```

2022-10-04 12:13 UTC, Sachin-chaurasiya commented on README.md
> +6. When you are done, stop the development server by pressing Ctrl+C in the terminal.
```suggestion
6. Stop the development server by pressing Ctrl+C in the terminal.
```

2022-10-04 19:20 UTC, Misterr-H commented
@Sachin-chaurasiya #2

2022-10-04 19:22 UTC, Sachin-chaurasiya commented
> @Sachin-chaurasiya #2 

@Misterr-H , Yeah can you link this issue to your PR?

2022-10-04 19:56 UTC, Misterr-H commented
@Sachin-chaurasiya , umm sorry but how to do that?

2022-10-05 05:05 UTC, Sachin-chaurasiya approved these changes

2022-10-20 07:24 UTC, atapas approved these changes

2022-10-20 07:24 UTC, merged