Contribute to docs
reactplay/docs pull request #51
Opened 2023-04-07 09:27 UTC by joypoddar

Kindly read thoroughly and suggest changes.

Closes #50

2023-04-13 09:23 UTC, atapas requested changes
Suggested Changes.

2023-04-13 10:04 UTC, joypoddar commented on docs/How-To-Guides/Contribute/contribute-to-docs.md
> +- improve the documentation
> So this doc should talk about the over all contributions that some one can make on ReactPlay. Not on the docs project alone.
> 
> So Rephrase it and add things like,
> 
> * Create Plays(Link to Create play doc)
> * Do Feature enhancements(Link to the feature create)
> * Test and Find Bug(Link to bugs create)
> * Improve docs(Link to the doc repo)
> * Manage our social handles
> * Give us the feedback, suggestions, help improving our UX
> * Be an advocate of ReactPlay and help us arranging events, getting sponsorship and support.
> * Write articles on our blog

Great suggestion. I can add a lot of things mentioned above. 

So, regarding what you said about this doc serving as a general contribution guide, I had the same question. please refer to [this](https://github.com/reactplay/docs/issues/50#issuecomment-1498874608) and let me know what to do.

2023-04-18 16:28 UTC, Sachin-chaurasiya requested changes

2023-04-18 16:28 UTC, Sachin-chaurasiya commented on src/css/custom.css
> +.first-issue {
```suggestion
.good-first-issue-badge {
```

2023-04-19 14:30 UTC, Sachin-chaurasiya requested changes

2023-04-19 14:30 UTC, Sachin-chaurasiya commented on docs/contribution-guide.md
> +:::
Can we update the className here as well?

2023-04-19 16:36 UTC, Sachin-chaurasiya commented on src/css/custom.css
> +}
@joypoddar , are we using this class somewhere?

2023-04-22 03:00 UTC, Sachin-chaurasiya approved these changes
Great work @joypoddar  🙌🏻,
Thanks for the contributions ✨

2023-04-29 07:29 UTC, atapas approved these changes

2023-04-29 07:29 UTC, merged