Localization ReactPlay In Bengali
reactplay/docs pull request #64
Opened 2023-07-06 10:13 UTC by Nargis21

As a user of ReactPlay, I would like to suggest the localization of the website in the Bengali language. By providing content in the native language of Bangla-speaking users, ReactPlay can greatly enhance the user experience. Users will feel more comfortable navigating the website, understanding instructions, and accessing features without any language barriers. It will make the website more accessible and user-friendly, attracting a wider audience. I completed the localization in Bengali.

2023-09-06 05:29 UTC, uiSubho98 commented
Subhojit Dutta

2023-09-07 09:22 UTC, atapas commented
@uiSubho98 

Thanks for volunteering to review it.

Please go page by page using the preview link above.

Do these pages first:

- [ ] https://docs.reactplay.io/
- [ ] https://docs.reactplay.io/contribution-guide
- [ ] https://docs.reactplay.io/local-development

If you have the review comments, please post them on the PR itself. I have added you ad the reviewer now.

2023-09-29 06:38 UTC, priyankarpal requested changes
please fix the spelling 
![image](https://github.com/reactplay/docs/assets/88102392/10b9e227-a93e-4ce0-a5ca-f1bf44374714)

2023-09-29 11:26 UTC, Nargis21 commented
Hey @priyankarpal, Is it okay? actually, it looks like this from my side,
![image](https://github.com/reactplay/docs/assets/96917167/e5042c67-55a8-49a7-b86e-eeb0b977e347)

2023-09-29 11:29 UTC, priyankarpal commented
> Hey @priyankarpal, Is it okay? actually, it looks like this from my side, but don't know why the letters broken from your end. ![image](https://user-images.githubusercontent.com/96917167/271555753-e5042c67-55a8-49a7-b86e-eeb0b977e347.png)

yeah! now it's ok

2023-10-12 04:43 UTC, priyankarpal requested changes
@Nargis21 please check

2023-10-12 04:43 UTC, priyankarpal commented on i18n/bn/docusaurus-plugin-content-docs/current/local-development.md
> +```
```suggestion
```bash

REACT_APP_PLAY_API_URL=https://api.github.com/repos/reactplay
REACT_APP_NHOST_BACKEND_URL=https://rgkjmwftqtbpayoyolwh.nhost.run
REACT_APP_NHOST_VERSION=v1
REACT_APP_NHOST_ENDPOINT=graphql
REACT_APP_PLAY_WEB_SVC=https://api.reactplay.io/.netlify/functions/server
DISABLE_ESLINT_PLUGIN=true
REACT_APP_ACTIVITIES_ON=true
REACT_APP_ACTIVITY_ID=hackrplay
REACT_APP_DADJOKES_URL=https://jokeapi-v2.p.rapidapi.com/joke/
REACT_APP_DADJOKES_APIKEY='b71df95c75msha446fab91d0e935p1d0262jsn1d938cb85502'
REACT_APP_DADJOKES_APIHOST='jokeapi-v2.p.rapidapi.com'

```

2023-10-12 05:03 UTC, Nargis21 commented on i18n/bn/docusaurus-plugin-content-docs/current/local-development.md
> +```
@priyankarpal Done!

2023-10-12 05:06 UTC, Nargis21 commented on i18n/bn/docusaurus-plugin-content-docs/current/local-development.md
> +```
@priyankarpal Done!

2023-10-12 05:23 UTC, priyankarpal approved these changes

2023-10-12 05:26 UTC, atapas approved these changes

2023-10-12 05:27 UTC, merged