[Feature] - How to style a play
reactplay/docs pull request #67
Opened 2023-07-06 11:04 UTC by supminn

- Fixes #55

2023-07-06 11:16 UTC, atapas reviewed
@supminn Looks good.

Can you also add a note somewhere not to override the style using !important.

2023-07-10 08:06 UTC, atapas approved these changes
Looks good to me.

2023-07-11 09:15 UTC, joshi-kaushal requested changes

2023-07-11 09:15 UTC, joshi-kaushal commented on docs/How-To-Guides/how-to-style-play.md
> +- Use CSS libraries that provide additional features such as scoped styles and automatic vendor prefixing. ReactPlay has been configured to support Tailwind CSS.
We should add a separate point regarding the use of Tailwind CSS.

2023-08-14 04:35 UTC, joshi-kaushal commented on docs/How-To-Guides/how-to-style-play.md
> +  For example, instead of using inline styles like this:
remove extra space

2023-08-14 04:38 UTC, joshi-kaushal commented on docs/How-To-Guides/how-to-style-play.md
> +- Use CSS libraries that provide additional features such as scoped styles and automatic vendor prefixing. ReactPlay has been configured to support Tailwind CSS.
1. [Scope style](https://developer.mozilla.org/en-US/docs/Web/CSS/:scope)
2. [automatic vendor prefixing](https://css-tricks.com/autoprefixer/)

Check if these links are correct and add them if they are. Let's resolve it.

2023-09-05 06:58 UTC, joshi-kaushal approved these changes

2023-09-05 08:14 UTC, atapas approved these changes

2023-09-05 08:15 UTC, merged